version: 2

sources:
  - name: raw_files
    database: >
      {%- if target.name == "default" -%}
        airbnb_raw_for_dev
      {%- elif target.name == "prod" -%}
        airbnb_raw
      {%- else -%}
        invalid_database
      {%- endif -%} 
    schema: raw  
    tables:
      - name: raw_reviews
      - name: raw_listings